service: cloudmusic
frameworkVersion: '3'

provider:
  name: aws
  memorySize: 2048
  timeout: 15
  stage: dev
  region: ap-southeast-1
  runtime: nodejs14.x

functions:
  music:
    handler: handler.music
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      NODE_ENV: development  
